### ISSUE TITLE
｀npm install｀后还要手工安装各种缺失的依赖！

### ISSUE THREAD

**Issue by ifcheung2012** [JasonBai007/React#5]
｀npm install｀后还要手工安装各种缺失的依赖，及其繁琐，难道是我本地环境的问题？是不是你有些包都安装到全局了？

**Comment by JasonBai007** [comment]
我这边是不用的，很有可能是你install的时候没有安装完整，需要安装正式结束后才可以。

**Comment by ifcheung2012** [comment]
我本地的库就安装了这么多：

├── gulp-babel@6.1.2  
├── hexo@3.2.0  
├── jsx@0.9.89  
├── jsx-loader@0.13.2  
└── react-native-cli@0.2.0  

  

其他依赖都是在项目里save的，估计是这个原因，你这个项目的部分依赖包应该是-g了。

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On 5月 25 2016, at 9:10 上午, Jason Bai &lt;notifications@github.com&gt; wrote:  

> 我这边是不用的，很有可能是你install的时候没有安装完整，需要安装正式结束后才可以。

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/JasonBa
i007/React/issues/5#issuecomment-221447293)![](https://github.com/notification
s/beacon/AB7Vqp3Yoh_C6ja0mjCXURUFAyXTgGnAks5qE6GNgaJpZM4ImCrs.gif)

**Comment by chendaole** [comment]
我这边之前也是这样，后来使用nodejs V6.2.0 才解决的，建议可以试一下，如果是linux下建议使用源码安装会好一些。
